### ISSUE TITLE
missing images referenced in app.py

### ISSUE THREAD

**Issue by senthilnayagam** [mv-lab/InstructIR#4]
missing images referenced in app.py

images/a0010.jpg
https://github.com/mv-lab/InstructIR/blob/bc395f6be3e5c0106ec22e105608b701373f0334/app.py#L125

images/real_fog.png
https://github.com/mv-lab/InstructIR/blob/bc395f6be3e5c0106ec22e105608b701373f0334/app.py#L126

**Comment by ffdown** [comment]
add anyything and rename =))
