### ISSUE TITLE
Congratulations to your great work! We have made an automaticversion based on InstructIR!

### ISSUE THREAD

**Issue by teowu** [mv-lab/InstructIR#6]
Nice work! The results are impressive, good text control. 

As the author of Q-Instruct (can query low-level degradations in images), I have made a simple concatenation between it (query Q-Instruct with `How to improve the quality of the image?`) and the InstructIR model, and allows users to **bypass the step to input prompt, and restore images automatically.**

<img width="1603" alt="Screenshot 2024-02-02 at 1 54 23 AM" src="https://github.com/mv-lab/InstructIR/assets/38696372/22ad73ca-7c4b-4b7b-b65b-246e84b5f532">

Here is the link to our demo: https://huggingface.co/spaces/teowu/Q-Instruct-Plus. We hope that we can keep an exchange in that.

Best
Haoning, Author of Q-Instruct

**Comment by mv-lab** [comment]
👍🏼 sent you an email (if you didn't get it, pls send me an email)
