### ISSUE TITLE
training and testing code

### ISSUE THREAD

**Issue by hlinqiao** [mv-lab/InstructIR#8]
Interested in your paper, can you share your training and testing code? Thank you very much!

**Comment by sentinel8b** [comment]
I'm also interested in training and testing code for this great work. Please consider sharing training and test codes for research purpose.

**Comment by mawei-north** [comment]
I'm also interested in training and testing code for this great work. Can you share your training and testing code? Thank you very much!

**Comment by mv-lab** [comment]
I will update the test code and all test results these days (working on that rn)

**Comment by mv-lab** [comment]
Hello @sentinel8b @hlinqiao @mawei-north I added the test code to generate all the results and calculate metrics.
everything in commit https://github.com/mv-lab/InstructIR/commit/d5417e4ac9006358502a545d7b807f5807799312

You can [download all the test datasets](https://drive.google.com/file/d/11wGsKOMDVrBlsle4xtzORPLZAsGhel8c/view?usp=sharing) for all-in-one restoration.

Check the instructions below to run `eval_instructir.py` and get all the metrics and results for all-in-one restoration.

You can download all the qualitative results here [instructir_results.zip](https://github.com/mv-lab/InstructIR/releases/download/instructir-results/instructir_results.zip)
